export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          display_name: string | null;
          role: string;
          plan: string;
          status: string;
          active_project_id: string | null;
          ai_creative_enabled: boolean;
          ai_organizational_enabled: boolean;
          openai_api_key_encrypted: string | null;
          openai_api_key_last4: string | null;
          openai_api_key_updated_at: string | null;
          created_at: string;
          updated_at: string;
          last_login_at: string | null;
        };
        Insert: {
          id: string;
          email?: string | null;
          display_name?: string | null;
          role?: string;
          plan?: string;
          status?: string;
          active_project_id?: string | null;
          ai_creative_enabled?: boolean;
          ai_organizational_enabled?: boolean;
          openai_api_key_encrypted?: string | null;
          openai_api_key_last4?: string | null;
          openai_api_key_updated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string | null;
          display_name?: string | null;
          role?: string;
          plan?: string;
          status?: string;
          active_project_id?: string | null;
          ai_creative_enabled?: boolean;
          ai_organizational_enabled?: boolean;
          openai_api_key_encrypted?: string | null;
          openai_api_key_last4?: string | null;
          openai_api_key_updated_at?: string | null;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
        };
        Relationships: [];
      };
      projects: {
        Row: {
          id: string;
          user_id: string;
          owner_id: string;
          title: string;
          slug: string | null;
          summary: string | null;
          description: string | null;
          genre: string | null;
          tone: string | null;
          themes: string[];
          timeline_start_year: number | null;
          timeline_end_year: number | null;
          default_calendar_system_id: string | null;
          primary_point_of_view_style: string | null;
          writing_status: string | null;
          book_order_mode: string | null;
          notes_root_id: string | null;
          settings: Json;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          owner_id: string;
          title: string;
          slug?: string | null;
          summary?: string | null;
          description?: string | null;
          genre?: string | null;
          tone?: string | null;
          themes?: string[];
          timeline_start_year?: number | null;
          timeline_end_year?: number | null;
          default_calendar_system_id?: string | null;
          primary_point_of_view_style?: string | null;
          writing_status?: string | null;
          book_order_mode?: string | null;
          notes_root_id?: string | null;
          settings?: Json;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          owner_id?: string;
          title?: string;
          slug?: string | null;
          summary?: string | null;
          description?: string | null;
          genre?: string | null;
          tone?: string | null;
          themes?: string[];
          timeline_start_year?: number | null;
          timeline_end_year?: number | null;
          default_calendar_system_id?: string | null;
          primary_point_of_view_style?: string | null;
          writing_status?: string | null;
          book_order_mode?: string | null;
          notes_root_id?: string | null;
          settings?: Json;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      books: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          series_order: number | null;
          internal_chronology_start: number | null;
          internal_chronology_end: number | null;
          premise: string;
          draft_stage: string;
          word_count_target: number | null;
          word_count_current: number;
          primary_themes: string[];
          main_characters: string[];
          key_locations: string[];
          related_plot_threads: string[];
          chapter_ids: string[];
          scene_ids: string[];
          timeline_event_ids: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          series_order?: number | null;
          internal_chronology_start?: number | null;
          internal_chronology_end?: number | null;
          premise?: string;
          draft_stage: string;
          word_count_target?: number | null;
          word_count_current?: number;
          primary_themes?: string[];
          main_characters?: string[];
          key_locations?: string[];
          related_plot_threads?: string[];
          chapter_ids?: string[];
          scene_ids?: string[];
          timeline_event_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          title?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          series_order?: number | null;
          internal_chronology_start?: number | null;
          internal_chronology_end?: number | null;
          premise?: string;
          draft_stage?: string;
          word_count_target?: number | null;
          word_count_current?: number;
          primary_themes?: string[];
          main_characters?: string[];
          key_locations?: string[];
          related_plot_threads?: string[];
          chapter_ids?: string[];
          scene_ids?: string[];
          timeline_event_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      chapters: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          book_id: string | null;
          chapter_number: number | null;
          purpose: string;
          point_of_view_character_id: string | null;
          timeline_event_ids: string[];
          scene_ids: string[];
          location_ids: string[];
          character_ids: string[];
          plot_thread_ids: string[];
          foreshadows: string[];
          payoffs: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          book_id?: string | null;
          chapter_number?: number | null;
          purpose?: string;
          point_of_view_character_id?: string | null;
          timeline_event_ids?: string[];
          scene_ids?: string[];
          location_ids?: string[];
          character_ids?: string[];
          plot_thread_ids?: string[];
          foreshadows?: string[];
          payoffs?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          title?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          book_id?: string | null;
          chapter_number?: number | null;
          purpose?: string;
          point_of_view_character_id?: string | null;
          timeline_event_ids?: string[];
          scene_ids?: string[];
          location_ids?: string[];
          character_ids?: string[];
          plot_thread_ids?: string[];
          foreshadows?: string[];
          payoffs?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      characters: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          aliases: string[];
          character_type: string;
          importance_level: string;
          birth_year: number | null;
          death_year: number | null;
          apparent_age: string;
          actual_age: string;
          species_id: string | null;
          culture_ids: string[];
          faction_ids: string[];
          religion_ids: string[];
          language_ids: string[];
          home_location_id: string | null;
          current_location_id: string | null;
          occupation: string[];
          skills: string[];
          traits: string[];
          flaws: string[];
          motivations: string[];
          fears: string[];
          secrets: string[];
          beliefs: string[];
          appearance: string;
          voice_profile: string;
          arc_summary: string;
          arc_start_state: string;
          arc_end_state: string;
          key_relationship_ids: string[];
          timeline_event_ids: string[];
          book_ids: string[];
          chapter_ids: string[];
          scene_ids: string[];
          important_items: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          aliases?: string[];
          character_type: string;
          importance_level: string;
          birth_year?: number | null;
          death_year?: number | null;
          apparent_age?: string;
          actual_age?: string;
          species_id?: string | null;
          culture_ids?: string[];
          faction_ids?: string[];
          religion_ids?: string[];
          language_ids?: string[];
          home_location_id?: string | null;
          current_location_id?: string | null;
          occupation?: string[];
          skills?: string[];
          traits?: string[];
          flaws?: string[];
          motivations?: string[];
          fears?: string[];
          secrets?: string[];
          beliefs?: string[];
          appearance?: string;
          voice_profile?: string;
          arc_summary?: string;
          arc_start_state?: string;
          arc_end_state?: string;
          key_relationship_ids?: string[];
          timeline_event_ids?: string[];
          book_ids?: string[];
          chapter_ids?: string[];
          scene_ids?: string[];
          important_items?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          name?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          aliases?: string[];
          character_type?: string;
          importance_level?: string;
          birth_year?: number | null;
          death_year?: number | null;
          apparent_age?: string;
          actual_age?: string;
          species_id?: string | null;
          culture_ids?: string[];
          faction_ids?: string[];
          religion_ids?: string[];
          language_ids?: string[];
          home_location_id?: string | null;
          current_location_id?: string | null;
          occupation?: string[];
          skills?: string[];
          traits?: string[];
          flaws?: string[];
          motivations?: string[];
          fears?: string[];
          secrets?: string[];
          beliefs?: string[];
          appearance?: string;
          voice_profile?: string;
          arc_summary?: string;
          arc_start_state?: string;
          arc_end_state?: string;
          key_relationship_ids?: string[];
          timeline_event_ids?: string[];
          book_ids?: string[];
          chapter_ids?: string[];
          scene_ids?: string[];
          important_items?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      scenes: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          book_id: string | null;
          chapter_id: string | null;
          scene_number: number | null;
          scene_type: string;
          point_of_view_character_id: string | null;
          goal: string;
          conflict: string;
          outcome: string;
          text_draft: string;
          timeline_event_ids: string[];
          character_ids: string[];
          location_ids: string[];
          plot_thread_ids: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          book_id?: string | null;
          chapter_id?: string | null;
          scene_number?: number | null;
          scene_type: string;
          point_of_view_character_id?: string | null;
          goal?: string;
          conflict?: string;
          outcome?: string;
          text_draft?: string;
          timeline_event_ids?: string[];
          character_ids?: string[];
          location_ids?: string[];
          plot_thread_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          title?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          book_id?: string | null;
          chapter_id?: string | null;
          scene_number?: number | null;
          scene_type?: string;
          point_of_view_character_id?: string | null;
          goal?: string;
          conflict?: string;
          outcome?: string;
          text_draft?: string;
          timeline_event_ids?: string[];
          character_ids?: string[];
          location_ids?: string[];
          plot_thread_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      relationships: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          relationship_type: string;
          entity_a_type: string;
          entity_a_id: string;
          entity_b_type: string;
          entity_b_id: string;
          dynamic_status: string;
          history: string;
          tensions: string[];
          strengths: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          relationship_type: string;
          entity_a_type: string;
          entity_a_id: string;
          entity_b_type: string;
          entity_b_id: string;
          dynamic_status?: string;
          history?: string;
          tensions?: string[];
          strengths?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          title?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          relationship_type?: string;
          entity_a_type?: string;
          entity_a_id?: string;
          entity_b_type?: string;
          entity_b_id?: string;
          dynamic_status?: string;
          history?: string;
          tensions?: string[];
          strengths?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      cultures: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          core_values: string[];
          traditions: string[];
          associated_location_ids: string[];
          language_ids: string[];
          religion_ids: string[];
          faction_ids: string[];
          era_ids: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          core_values?: string[];
          traditions?: string[];
          associated_location_ids?: string[];
          language_ids?: string[];
          religion_ids?: string[];
          faction_ids?: string[];
          era_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          name?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          core_values?: string[];
          traditions?: string[];
          associated_location_ids?: string[];
          language_ids?: string[];
          religion_ids?: string[];
          faction_ids?: string[];
          era_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      factions: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          faction_type: string;
          founded_year: number | null;
          ended_year: number | null;
          leader_character_ids: string[];
          base_location_ids: string[];
          culture_ids: string[];
          religion_ids: string[];
          government_id: string | null;
          goals: string[];
          resources: string[];
          rivals: string[];
          allies: string[];
          timeline_event_ids: string[];
          book_ids: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          faction_type: string;
          founded_year?: number | null;
          ended_year?: number | null;
          leader_character_ids?: string[];
          base_location_ids?: string[];
          culture_ids?: string[];
          religion_ids?: string[];
          government_id?: string | null;
          goals?: string[];
          resources?: string[];
          rivals?: string[];
          allies?: string[];
          timeline_event_ids?: string[];
          book_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          name?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          faction_type?: string;
          founded_year?: number | null;
          ended_year?: number | null;
          leader_character_ids?: string[];
          base_location_ids?: string[];
          culture_ids?: string[];
          religion_ids?: string[];
          government_id?: string | null;
          goals?: string[];
          resources?: string[];
          rivals?: string[];
          allies?: string[];
          timeline_event_ids?: string[];
          book_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      locations: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          location_type: string;
          parent_location_id: string | null;
          child_location_ids: string[];
          era_ids: string[];
          culture_ids: string[];
          faction_ids: string[];
          population_notes: string;
          climate: string;
          geography: string;
          architecture: string;
          economy: string;
          customs: string[];
          danger_level: string;
          notable_features: string[];
          timeline_event_ids: string[];
          book_ids: string[];
          character_ids: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          location_type?: string;
          parent_location_id?: string | null;
          child_location_ids?: string[];
          era_ids?: string[];
          culture_ids?: string[];
          faction_ids?: string[];
          population_notes?: string;
          climate?: string;
          geography?: string;
          architecture?: string;
          economy?: string;
          customs?: string[];
          danger_level?: string;
          notable_features?: string[];
          timeline_event_ids?: string[];
          book_ids?: string[];
          character_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          name?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          location_type?: string;
          parent_location_id?: string | null;
          child_location_ids?: string[];
          era_ids?: string[];
          culture_ids?: string[];
          faction_ids?: string[];
          population_notes?: string;
          climate?: string;
          geography?: string;
          architecture?: string;
          economy?: string;
          customs?: string[];
          danger_level?: string;
          notable_features?: string[];
          timeline_event_ids?: string[];
          book_ids?: string[];
          character_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      religions: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          deity_or_focus: string;
          belief_system_type: string;
          core_beliefs: string[];
          rituals: string[];
          holy_sites: string[];
          associated_cultures: string[];
          associated_organizations: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          deity_or_focus?: string;
          belief_system_type?: string;
          core_beliefs?: string[];
          rituals?: string[];
          holy_sites?: string[];
          associated_cultures?: string[];
          associated_organizations?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          name?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          deity_or_focus?: string;
          belief_system_type?: string;
          core_beliefs?: string[];
          rituals?: string[];
          holy_sites?: string[];
          associated_cultures?: string[];
          associated_organizations?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      governments: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          government_type: string;
          seat_location_id: string | null;
          leader_titles: string[];
          jurisdiction_notes: string;
          faction_ids: string[];
          organization_ids: string[];
          law_priorities: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          government_type: string;
          seat_location_id?: string | null;
          leader_titles?: string[];
          jurisdiction_notes?: string;
          faction_ids?: string[];
          organization_ids?: string[];
          law_priorities?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          name?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          government_type?: string;
          seat_location_id?: string | null;
          leader_titles?: string[];
          jurisdiction_notes?: string;
          faction_ids?: string[];
          organization_ids?: string[];
          law_priorities?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      organizations: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          organization_type: string;
          founded_year: number | null;
          base_location_ids: string[];
          leader_titles: string[];
          member_count_estimate: number | null;
          goals: string[];
          resources: string[];
          alliances: string[];
          rivals: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          organization_type: string;
          founded_year?: number | null;
          base_location_ids?: string[];
          leader_titles?: string[];
          member_count_estimate?: number | null;
          goals?: string[];
          resources?: string[];
          alliances?: string[];
          rivals?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          name?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          organization_type?: string;
          founded_year?: number | null;
          base_location_ids?: string[];
          leader_titles?: string[];
          member_count_estimate?: number | null;
          goals?: string[];
          resources?: string[];
          alliances?: string[];
          rivals?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      plot_threads: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          thread_type: string;
          introduced_in_book_id: string | null;
          resolved_in_book_id: string | null;
          character_ids: string[];
          timeline_event_ids: string[];
          book_ids: string[];
          chapter_ids: string[];
          scene_ids: string[];
          theme_ids: string[];
          note_ids: string[];
          setup_notes: string[];
          payoff_notes: string[];
          open_questions: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          thread_type: string;
          introduced_in_book_id?: string | null;
          resolved_in_book_id?: string | null;
          character_ids?: string[];
          timeline_event_ids?: string[];
          book_ids?: string[];
          chapter_ids?: string[];
          scene_ids?: string[];
          theme_ids?: string[];
          note_ids?: string[];
          setup_notes?: string[];
          payoff_notes?: string[];
          open_questions?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          title?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          thread_type?: string;
          introduced_in_book_id?: string | null;
          resolved_in_book_id?: string | null;
          character_ids?: string[];
          timeline_event_ids?: string[];
          book_ids?: string[];
          chapter_ids?: string[];
          scene_ids?: string[];
          theme_ids?: string[];
          note_ids?: string[];
          setup_notes?: string[];
          payoff_notes?: string[];
          open_questions?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      outlines: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          outline_type: string;
          scope: string;
          act_structure: string[];
          milestones: string[];
          book_ids: string[];
          thread_ids: string[];
          note_ids: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          outline_type: string;
          scope?: string;
          act_structure?: string[];
          milestones?: string[];
          book_ids?: string[];
          thread_ids?: string[];
          note_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          title?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          outline_type?: string;
          scope?: string;
          act_structure?: string[];
          milestones?: string[];
          book_ids?: string[];
          thread_ids?: string[];
          note_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      glossary_terms: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          term: string;
          definition: string;
          category: string;
          related_entity_types: string[];
          related_entity_ids: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          term: string;
          definition?: string;
          category?: string;
          related_entity_types?: string[];
          related_entity_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          title?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          term?: string;
          definition?: string;
          category?: string;
          related_entity_types?: string[];
          related_entity_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notes: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          content: string;
          note_type: string;
          linked_entity_type: string | null;
          linked_entity_id: string | null;
          linked_book_ids: string[];
          linked_chapter_ids: string[];
          linked_character_ids: string[];
          linked_location_ids: string[];
          linked_event_ids: string[];
          linked_thread_ids: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          content?: string;
          note_type?: string;
          linked_entity_type?: string | null;
          linked_entity_id?: string | null;
          linked_book_ids?: string[];
          linked_chapter_ids?: string[];
          linked_character_ids?: string[];
          linked_location_ids?: string[];
          linked_event_ids?: string[];
          linked_thread_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          title?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          content?: string;
          note_type?: string;
          linked_entity_type?: string | null;
          linked_entity_id?: string | null;
          linked_book_ids?: string[];
          linked_chapter_ids?: string[];
          linked_character_ids?: string[];
          linked_location_ids?: string[];
          linked_event_ids?: string[];
          linked_thread_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      retcons: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          old_canon: string;
          new_canon: string;
          reason: string;
          impact_level: string;
          affected_entity_types: string[];
          affected_entity_ids: string[];
          resolved: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          old_canon?: string;
          new_canon?: string;
          reason?: string;
          impact_level: string;
          affected_entity_types?: string[];
          affected_entity_ids?: string[];
          resolved?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          title?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          old_canon?: string;
          new_canon?: string;
          reason?: string;
          impact_level?: string;
          affected_entity_types?: string[];
          affected_entity_ids?: string[];
          resolved?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      attachments: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          attachment_type: string;
          storage_status: string;
          file_name: string;
          mime_type: string;
          source_note: string;
          url: string | null;
          storage_bucket: string | null;
          storage_path: string | null;
          file_size_bytes: number | null;
          linked_entity_type: string | null;
          linked_entity_id: string | null;
          linked_note_ids: string[];
          linked_outline_ids: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          attachment_type: string;
          storage_status: string;
          file_name?: string;
          mime_type?: string;
          source_note?: string;
          url?: string | null;
          storage_bucket?: string | null;
          storage_path?: string | null;
          file_size_bytes?: number | null;
          linked_entity_type?: string | null;
          linked_entity_id?: string | null;
          linked_note_ids?: string[];
          linked_outline_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          title?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          attachment_type?: string;
          storage_status?: string;
          file_name?: string;
          mime_type?: string;
          source_note?: string;
          url?: string | null;
          storage_bucket?: string | null;
          storage_path?: string | null;
          file_size_bytes?: number | null;
          linked_entity_type?: string | null;
          linked_entity_id?: string | null;
          linked_note_ids?: string[];
          linked_outline_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      ai_sessions: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          session_type: string;
          provider: string;
          model: string;
          purpose: string;
          prompt_excerpt: string;
          output_summary: string;
          source_text: string;
          source_guidance: string;
          extraction_status: string;
          extraction_error: string;
          extraction_model: string;
          extraction_result: Json | null;
          workflow_state: Json | null;
          linked_entity_types: string[];
          linked_entity_ids: string[];
          messages_count: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          session_type: string;
          provider?: string;
          model?: string;
          purpose?: string;
          prompt_excerpt?: string;
          output_summary?: string;
          source_text?: string;
          source_guidance?: string;
          extraction_status?: string;
          extraction_error?: string;
          extraction_model?: string;
          extraction_result?: Json | null;
          workflow_state?: Json | null;
          linked_entity_types?: string[];
          linked_entity_ids?: string[];
          messages_count?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          title?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          session_type?: string;
          provider?: string;
          model?: string;
          purpose?: string;
          prompt_excerpt?: string;
          output_summary?: string;
          source_text?: string;
          source_guidance?: string;
          extraction_status?: string;
          extraction_error?: string;
          extraction_model?: string;
          extraction_result?: Json | null;
          workflow_state?: Json | null;
          linked_entity_types?: string[];
          linked_entity_ids?: string[];
          messages_count?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      eras: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          start_year: number | null;
          end_year: number | null;
          defining_events: string[];
          key_locations: string[];
          key_factions: string[];
          dominant_themes: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          start_year?: number | null;
          end_year?: number | null;
          defining_events?: string[];
          key_locations?: string[];
          key_factions?: string[];
          dominant_themes?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          name?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          start_year?: number | null;
          end_year?: number | null;
          defining_events?: string[];
          key_locations?: string[];
          key_factions?: string[];
          dominant_themes?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      themes: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          central_question: string;
          associated_book_ids: string[];
          associated_character_ids: string[];
          associated_timeline_event_ids: string[];
          associated_era_ids: string[];
          associated_plot_thread_ids: string[];
          motifs: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          central_question?: string;
          associated_book_ids?: string[];
          associated_character_ids?: string[];
          associated_timeline_event_ids?: string[];
          associated_era_ids?: string[];
          associated_plot_thread_ids?: string[];
          motifs?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          name?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          central_question?: string;
          associated_book_ids?: string[];
          associated_character_ids?: string[];
          associated_timeline_event_ids?: string[];
          associated_era_ids?: string[];
          associated_plot_thread_ids?: string[];
          motifs?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      languages: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          language_family: string;
          writing_system: string;
          primary_regions: string[];
          dialects: string[];
          loan_sources: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          language_family?: string;
          writing_system?: string;
          primary_regions?: string[];
          dialects?: string[];
          loan_sources?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          name?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          language_family?: string;
          writing_system?: string;
          primary_regions?: string[];
          dialects?: string[];
          loan_sources?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      species: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          origin: string;
          lifespan: string;
          appearance: string;
          biology: string;
          reproduction: string;
          diet: string;
          psychology: string;
          social_structure: string;
          abilities: string[];
          limitations: string[];
          notable_subgroups: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          origin?: string;
          lifespan?: string;
          appearance?: string;
          biology?: string;
          reproduction?: string;
          diet?: string;
          psychology?: string;
          social_structure?: string;
          abilities?: string[];
          limitations?: string[];
          notable_subgroups?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          name?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          origin?: string;
          lifespan?: string;
          appearance?: string;
          biology?: string;
          reproduction?: string;
          diet?: string;
          psychology?: string;
          social_structure?: string;
          abilities?: string[];
          limitations?: string[];
          notable_subgroups?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      items: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          item_type: string;
          owner_character_ids: string[];
          location_ids: string[];
          faction_ids: string[];
          created_year: number | null;
          material: string;
          abilities: string[];
          limitations: string[];
          symbolic_meaning: string;
          timeline_event_ids: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          item_type?: string;
          owner_character_ids?: string[];
          location_ids?: string[];
          faction_ids?: string[];
          created_year?: number | null;
          material?: string;
          abilities?: string[];
          limitations?: string[];
          symbolic_meaning?: string;
          timeline_event_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          name?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          item_type?: string;
          owner_character_ids?: string[];
          location_ids?: string[];
          faction_ids?: string[];
          created_year?: number | null;
          material?: string;
          abilities?: string[];
          limitations?: string[];
          symbolic_meaning?: string;
          timeline_event_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      technologies: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          technology_type: string;
          invented_year: number | null;
          inventor_notes: string;
          power_source: string;
          limitations: string[];
          associated_location_ids: string[];
          associated_faction_ids: string[];
          timeline_event_ids: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          name: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          technology_type?: string;
          invented_year?: number | null;
          inventor_notes?: string;
          power_source?: string;
          limitations?: string[];
          associated_location_ids?: string[];
          associated_faction_ids?: string[];
          timeline_event_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          name?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          technology_type?: string;
          invented_year?: number | null;
          inventor_notes?: string;
          power_source?: string;
          limitations?: string[];
          associated_location_ids?: string[];
          associated_faction_ids?: string[];
          timeline_event_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      timeline_events: {
        Row: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary: string;
          description: string;
          status: string;
          tags: string[];
          is_archived: boolean;
          canon_level: string;
          confidence: string;
          event_type: string;
          year_start: number | null;
          month_start: number | null;
          day_start: number | null;
          year_end: number | null;
          month_end: number | null;
          day_end: number | null;
          chronology_order: number | null;
          time_of_day_label: string;
          display_date_label: string;
          era_id: string | null;
          book_ids: string[];
          chapter_ids: string[];
          scene_ids: string[];
          character_ids: string[];
          location_ids: string[];
          faction_ids: string[];
          culture_ids: string[];
          technology_ids: string[];
          religion_ids: string[];
          plot_thread_ids: string[];
          theme_ids: string[];
          causes: string[];
          consequences: string[];
          predecessor_event_ids: string[];
          successor_event_ids: string[];
          public_wiki_summary: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          project_id: string;
          id: string;
          title: string;
          slug: string;
          summary?: string;
          description?: string;
          status: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level: string;
          confidence: string;
          event_type: string;
          year_start?: number | null;
          month_start?: number | null;
          day_start?: number | null;
          year_end?: number | null;
          month_end?: number | null;
          day_end?: number | null;
          chronology_order?: number | null;
          time_of_day_label?: string;
          display_date_label?: string;
          era_id?: string | null;
          book_ids?: string[];
          chapter_ids?: string[];
          scene_ids?: string[];
          character_ids?: string[];
          location_ids?: string[];
          faction_ids?: string[];
          culture_ids?: string[];
          technology_ids?: string[];
          religion_ids?: string[];
          plot_thread_ids?: string[];
          theme_ids?: string[];
          causes?: string[];
          consequences?: string[];
          predecessor_event_ids?: string[];
          successor_event_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          project_id?: string;
          id?: string;
          title?: string;
          slug?: string;
          summary?: string;
          description?: string;
          status?: string;
          tags?: string[];
          is_archived?: boolean;
          canon_level?: string;
          confidence?: string;
          event_type?: string;
          year_start?: number | null;
          month_start?: number | null;
          day_start?: number | null;
          year_end?: number | null;
          month_end?: number | null;
          day_end?: number | null;
          chronology_order?: number | null;
          time_of_day_label?: string;
          display_date_label?: string;
          era_id?: string | null;
          book_ids?: string[];
          chapter_ids?: string[];
          scene_ids?: string[];
          character_ids?: string[];
          location_ids?: string[];
          faction_ids?: string[];
          culture_ids?: string[];
          technology_ids?: string[];
          religion_ids?: string[];
          plot_thread_ids?: string[];
          theme_ids?: string[];
          causes?: string[];
          consequences?: string[];
          predecessor_event_ids?: string[];
          successor_event_ids?: string[];
          public_wiki_summary?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
